# Generated by Django 4.2.3 on 2023-08-05 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifytoken',
            old_name='access_toekn',
            new_name='access_token',
        ),
    ]
